### PR TITLE
Mustafa

### PR DESCRIPTION
**Pull request by mustafa-tanis21**
Added Base and Utilities 
Updated test case G12_106

Please check if the codes are correct and approve!

### CODE REVIEW

**Comment by dianadudic** [comment]
Nice job, Mustafa.

**Review by dianadudic — COMMENTED** [review]
I will wait for someone else to approve so they can inspect changes.

**Comment by volkan2018** [comment]
Good job Mustafa!

**Review by volkan2018 — COMMENTED** [review]
I wanted to add my review :)

**Comment by Saltanat2020** [comment]
Hi group 12!

**Pull request closed without merging**
